[package]
  name = "znotfireman/ohmyprvd-debugger"
  description = "Oh My Prvd is a delightful framework for next-generation Roblox game development."
  version = "0.1.0-alpha"
  authors = ["ImNotFireMan123"]
  realm = "shared"
  registry = "https://github.com/UpliftGames/wally-index"

  include = ["./lib", "./default.project.json"]
  exclude = ["DevPackages, packages"]

[dependencies]
  Fusion = "plainsour/lemon@0.3.0-dev.5.9"
  prvd = "znotfireman/ohmyprvd@0.2.0-dev.1"
