# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Oh My Prvd
site_url: https://team-fireworks.github.io/ohmyprvd
repo_url: https://github.com/team-fireworks/ohmyprvd

theme:
  name: material
  custom_dir: docs/assets/overrides
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: ompdoc-dark
      toggle:
        icon: octicons/sun-24
        title: Switch to light theme
    - media: "(prefers-color-scheme: light)"
      scheme: ompdoc-light
      toggle:
        icon: octicons/moon-24
        title: Switch to dark theme
  font:
    text: Inter
    code: JetBrains Mono
  logo: assets/logo.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/flame-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.suggest

nav:
  - Home: index.md
  - Learn:
    - learn/index.md
    - Installation: learn/installation.md
    - Providers: learn/providers.md
    - Ignition: learn/ignition.md
    - Net:
      - Net: learn/net/index.md
      - Events: learn/net/events.md
      - Functions: learn/net/functions.md
      - Middlewares: learn/net/middlewares.md
      - Namespaces: learn/net/namespaces.md
    - Components:
      - Components: learn/components/index.md
      - Usage: learn/components/usage.md
      - Attributes: learn/components/attributes.md
      - Inheritance: learn/components/inheritance.md
    - Advanced:
      - Modding: learn/advanced/modding.md
      - Execution Order: learn/advanced/execution-order.md
      - VSCode Snippets: learn/advanced/snippets.md
      - Alternatives: learn/advanced/alternatives.md
  - Examples:
    - examples/index.md
    - Projects:
      - Obby: examples/projects/obby.md
  - Reference:
    - reference/index.md
    - Error Messages: reference/error-messages.md
    - Core:
      - reference/core/index.md
      - Providers:
        - reference/core/providers/index.md
        - awaitIgnition: reference/core/providers/await-ignition.md
        - ignite: reference/core/providers/ignite.md
        - IgnitionStatus: reference/core/providers/ignition-status.md
        - onIgnition: reference/core/providers/on-ignition.md
        - Provider: reference/core/providers/provider.md
        - use: reference/core/providers/use.md
      - Loader:
        - reference/core/loader/index.md
        - loadChildren: reference/core/loader/load-children.md
        - loadDescendants: reference/core/loader/load-descendants.md
        - matchesName: reference/core/loader/matches-name.md
      - Modding:
        - reference/core/modding/index.md
        - getIgnitionOptions: reference/core/modding/get-ignition-options.md
        - onMethodImplemented: reference/core/modding/on-method-implemented.md
        - onProviderConstructed: reference/core/modding/on-provider-constructed.md
        - onProviderUsed: reference/core/modding/on-provider-used.md
      - Reflection:
        - reference/core/reflection/index.md
        - defineMetadata: reference/core/reflection/define-metadata.md
        - getMetadata: reference/core/reflection/get-metadata.md
        - deleteMetadata: reference/core/reflection/delete-metadata.md
      - Types:
        - reference/core/types/index.md
        - Options: reference/core/types/options.md
        - Provider: reference/core/types/provider.md

extra_css:
  - assets/theme/code.css
  - assets/theme/home.css
  - assets/theme/ompdoc.css
  - assets/theme/page.css

extra:
  version:
    provider: mike

plugins:
  - search
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

markdown_extensions:
  - toc:
      title: On this page
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

