# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Oh My Prvd
site_url: https://team-fireworks.github.io/ohmyprvd
repo_url: https://github.com/team-fireworks/ohmyprvd

theme:
  name: material
  custom_dir: docs/assets/overrides
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: ompdoc-dark
      toggle:
        icon: octicons/sun-24
        title: Switch to light theme
    - media: "(prefers-color-scheme: light)"
      scheme: ompdoc-light
      toggle:
        icon: octicons/moon-24
        title: Switch to dark theme
  font:
    text: Inter
    code: JetBrains Mono
  logo: assets/logo.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/flame-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.suggest

nav:
  - Home: index.md
  - Tutorials:
    - Get Started: tutorials/index.md
    - Installation: tutorials/installation.md
    - Providers: tutorials/providers.md
    - Ignition: tutorials/ignition.md
    - Net:
      - Net: tutorials/net/index.md
      - Events: tutorials/net/events.md
      - Functions: tutorials/net/functions.md
      - Middlewares: tutorials/net/middlewares.md
      - Namespaces: tutorials/net/namespaces.md
    - Components:
      - Components: tutorials/components/index.md
      - Usage: tutorials/components/usage.md
      - Attributes: tutorials/components/attributes.md
      - Inheritance: tutorials/components/inheritance.md
    - Advanced:
      - Modding: tutorials/advanced/modding.md
      - Execution Order: tutorials/advanced/execution-order.md
      - VSCode Snippets: tutorials/advanced/snippets.md
      - Alternatives: tutorials/advanced/alternatives.md
  - Examples:
    - examples/index.md
    - Projects:
      - Obby: examples/projects/obby.md
  - API Reference:
    - api-reference/index.md
    - Error Messages: api-reference/error-messages.md
    - Core:
      - api-reference/core/index.md
      - Members:
        - awaitIgnition: api-reference/core/members/await-ignition.md
        - defineMetadata: api-reference/core/members/define-metadata.md
        - deleteMetadata: api-reference/core/members/delete-metadata.md
        - getIgnitionOptions: api-reference/core/members/get-ignition-options.md
        - getMetadata: api-reference/core/members/get-metadata.md
        - ignite: api-reference/core/members/ignite.md
        - IgnitionStatus: api-reference/core/members/ignition-status.md
        - loadChildren: api-reference/core/members/load-children.md
        - loadDescendants: api-reference/core/members/load-descendants.md
        - onIgnition: api-reference/core/members/on-ignition.md
        - onMethodImplemented: api-reference/core/members/on-method-implemented.md
        - onProviderConstructed: api-reference/core/members/on-provider-constructed.md
        - onProviderUsed: api-reference/core/members/on-provider-used.md
        - Provider: api-reference/core/members/provider.md
        - use: api-reference/core/members/use.md
      - Types:
        - Options: api-reference/core/types/options.md
        - Provider: api-reference/core/types/provider.md

extra_css:
  - assets/theme/code.css
  - assets/theme/home.css
  - assets/theme/ompdoc.css
  - assets/theme/page.css

extra:
  version:
    provider: mike

plugins:
  - search
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

markdown_extensions:
  - toc:
      title: On this page
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

