[package]
  name = "znotfireman/ohmyprvd-lifecycles"
  description = "Implements a \"small\" amount of lifecycle events for providers."
  version = "0.1.0-alpha"
  authors = ["ImNotFireMan123"]
  realm = "shared"
  registry = "https://github.com/UpliftGames/wally-index"

  include = ["lib", "default.project.json"]
  exclude = ["DevPackages", "node_modules", "Packages"]

[dependencies]
  prvd = "znotfireman/ohmyprvd@0.1.1-alpha"
