[package]
  name = "znotfireman/ohmyprvd"
  description = "Oh My Prvd is a delightful framework for modern Roblox game development."
  version = "0.2.0-dev.4"
  authors = ["ImNotFireMan123"]
  realm = "shared"
  registry = "https://github.com/UpliftGames/wally-index"

  include = ["./lib", "./default.project.json"]
  exclude = ["node_modules"]
