[package]
  name = "znotfireman/ohmyprvd"
  description = "Oh My Prvd is a delightful framework for next-generation Roblox game development."
  version = "0.1.0-alpha"
  authors = ["ImNotFireMan123"]
  realm = "shared"
  registry = "https://github.com/UpliftGames/wally-index"

  include = ["lib", "default.project.json"]
  exclude = ["packages"]

[dev-dependencies]
  jest = "jsdotlua/jest@3.6.1-rc.2"
  jest_globals = "jsdotlua/jest-globals@3.6.1-rc.2"
