[package]
  name = "znotfireman/ohmyprvd-components"
  description = "Implements a component system for the Oh My Prvd Roblox framework."
  version = "0.2.0-dev.4"
  authors = ["ImNotFireMan123"]
  realm = "shared"
  registry = "https://github.com/UpliftGames/wally-index"

  include = ["./lib", "./default.project.json"]
  # exclude = ["Packages"]

[dependencies]
  prvd = "znotfireman/ohmyprvd@0.2.0-dev.1"
