name: Continous Integration

on:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              # ?????
            # - name: Install Rokit
            #   uses: CompeyDev/setup-rokit@v0.1.0
            #   with:
            #       token: ${{ secrets.GITHUB_TOKEN }}
            - name: Download Rokit
              run: |
                  case ${{ runner.os }} in
                    Linux) pattern="*linux-x86_64.zip" ;;
                    macOS) pattern="*macos-x86_64.zip" ;;
                    Windows) pattern="*windows-x86_64.zip" ;;
                  esac

                  gh release download --repo rojo-rbx/rokit --pattern $pattern
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              shell: bash

            - name: Install Rokit
              run: |
                  unzip rokit*.zip
                  ./rokit self-install

            - name: Delete artifacts
              run: |
                  rm rokit*.zip
                  if ${{ runner.os == 'Windows' }}; then
                    rm rokit.exe
                  else
                    rm rokit
                  fi
              shell: bash

            - name: Add Rokit to PATH
              if: runner.os != 'Windows'
              run: echo "$HOME/.rokit/bin" >> $GITHUB_PATH
              shell: bash

            - name: Add Rokit to PATH
              if: runner.os == 'Windows'
              run: echo "$HOME/.rokit/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
              shell: powershell

            - name: Create auth file
              run: |
                  cat > $HOME/.rokit/auth.toml << EOF
                  github = "${{ secrets.GITHUB_TOKEN }}"
                  EOF
              shell: bash

            - name: Discover manifest file
              id: manifest
              run: |
                  manifest_path=$(find . -maxdepth 1 -name "rokit.toml")
                  echo "::debug::Discovered manifest path: $manifest_path"
                  echo "path=$manifest_path" >> $GITHUB_OUTPUT
              shell: bash

            - name: Cache binaries
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.rokit/bin
                      ~/.rokit/tool-storage
                  key: ${{ runner.os }}-rokit-${{hashFiles(steps.manifest.outputs.path)}}

            - name: Install tools
              run: |
                  rokit install --no-trust-check
              shell: bash

            - name: Run Selene
              run: |
                  selene packages/
    formatting:
        name: Formatting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            # - name: Install Rokit
            #   uses: CompeyDev/setup-rokit@v0.1.0
            #   with:
            #       token: ${{ secrets.GITHUB_TOKEN }}
            # ?????
            # - name: Install Rokit
            #   uses: CompeyDev/setup-rokit@v0.1.0
            #   with:
            #       token: ${{ secrets.GITHUB_TOKEN }}
            # I know how diabolical this is but i cant stand this at all
            - name: Download Rokit
              run: |
                  case ${{ runner.os }} in
                    Linux) pattern="*linux-x86_64.zip" ;;
                    macOS) pattern="*macos-x86_64.zip" ;;
                    Windows) pattern="*windows-x86_64.zip" ;;
                  esac

                  gh release download --repo rojo-rbx/rokit --pattern $pattern
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              shell: bash

            - name: Install Rokit
              run: |
                  unzip rokit*.zip
                  ./rokit self-install

                  - name: Add Rokit to PATH
                  if: runner.os != 'Windows'
                  run: echo "$HOME/.rokit/bin" >> $GITHUB_PATH
                  shell: bash

            - name: Delete artifacts
              run: |
                  rm rokit*.zip
                  if ${{ runner.os == 'Windows' }}; then
                    rm rokit.exe
                  else
                    rm rokit
                  fi
              shell: bash

            - name: Add Rokit to PATH
              if: runner.os == 'Windows'
              run: echo "$HOME/.rokit/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
              shell: powershell

            - name: Create auth file
              run: |
                  cat > $HOME/.rokit/auth.toml << EOF
                  github = "${{ secrets.GITHUB_TOKEN }}"
                  EOF
              shell: bash

            - name: Discover manifest file
              id: manifest
              run: |
                  manifest_path=$(find . -maxdepth 1 -name "rokit.toml")
                  echo "::debug::Discovered manifest path: $manifest_path"
                  echo "path=$manifest_path" >> $GITHUB_OUTPUT
              shell: bash

            - name: Cache binaries
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.rokit/bin
                      ~/.rokit/tool-storage
                  key: ${{ runner.os }}-rokit-${{hashFiles(steps.manifest.outputs.path)}}

            - name: Install tools
              run: |
                  rokit install --no-trust-check
              shell: bash
            - name: Run Stylua
              uses: JohnnyMorganz/stylua-action@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  version: v0.20.0
                  args: --check packages/
