name: Documentation
on:
    push:
        branches:
            - main

env:
    VERSION: 0.2
    LABEL: "dev"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Install Python 3.x
              uses: actions/setup-python@v4
              with:
                  python-version: 3.x

            - name: Install setuptools (for mike)
              run: pip install --upgrade setuptools

            - name: Install MkDocs
              run: pip install mkdocs-material

            - name: Install mike
              run: pip install mike

            - name: Fetch gh-pages branch
              run: git fetch origin gh-pages --depth=1

            - name: Deploy latest documentation
              if: env.LABEL == 'release'
              run: mike deploy $VERSION latest --branch gh-pages --push

            - name: Set default version to latest
              if: env.LABEL == 'release'
              run: mike set-default latest --branch gh-pages --push

            - name: Deploy developer documentation
              if: env.LABEL == 'dev'
              run: mike deploy $VERSION --branch gh-pages --push
