name: Release

on:
    workflow_dispatch:
        inputs:
            release_tag:
                description: "The version to release starting with `v`"
                required: true
                type: string

            release_ref:
                description: "The branch, tag or SHA to checkout (default to latest)"
                default: ""
                type: string

permissions:
    contents: write

jobs:
    npm:
        name: Publish to NPM
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: 8
                  run_install: false
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version-file: "latest"
                  cache: pnpm
                  registry-url: https://registry.npmjs.org

            - name: Publish ohmyprvd
              shell: bash
              run: pnpm publish packages/ohmyprvd --access public --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish ohmyprvd-lifecycles
              shell: bash
              run: pnpm publish packages/ohmyprvd-lifecycles --access public --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    wally:
        needs: npm

        name: Publish to Wally
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: Roblox/setup-foreman@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - uses: ok-nick/setup-aftman@v0.4.2
            - name: Login to wally
              run: wally login --project-path packages/ohmyprvd --token ${{ secrets.WALLY_ACCESS_TOKEN }}

            - name: Publish ohmyprvd to wally
              run: wally publish --project-path packages/ohmyprvd

            - name: Publish ohmyprvd-lifecycles to wally
              run: wally publish --project-path packages/ohmyprvd-lifecycles

    release:
        needs: npm
        name: Create release
        runs-on: ubuntu-latest
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
        steps:
            - uses: actions/checkout@v4
            - name: Create tag
              run: |
                  git fetch --tags --no-recurse-submodules
                  if [ ! $(git tag -l ${{ inputs.release_tag }}) ]; then
                    git tag ${{ inputs.release_tag }}
                    git push origin ${{ inputs.release_tag }}
                  fi

            - name: Create release
              id: create_release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ inputs.release_tag }}
                  name: ${{ inputs.release_tag }}
                  draft: true
